[package]
name = "pvme"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.13", features = ["derive"] }
env_logger = "0.11.5"
polkavm = { git = "https://github.com/koute/polkavm" }
