[package]
name = "pvme"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive"] }
env_logger = "0.11.8"
polkavm = { git = "https://github.com/koute/polkavm", branch = "master" }
