set quiet
set dotenv-path := "../.env"

default: build run

run:
    printf "is_authorized: "
    pvme call main.pvm is_authorized

build:
    $DOCKER run --rm -v{{justfile_directory()}}:/opt pvm clang-18 \
        --target=riscv32 \
        -march=rv32emc \
        -mabi=ilp32e \
        -nostdlib \
        -nodefaultlibs \
        -fpic \
        -fPIE \
        -mrelax \
        -ffast-math \
        -gdwarf-5 \
        -g3 \
        -O3 \
        -fno-exceptions \
        -fno-rtti \
        -Wl,--error-limit=0 \
        -Wl,--emit-relocs \
        -Wl,--no-relax \
        -Wl,--entry=entry \
        main.c \
        -o main.elf
    polkatool link -s main.elf -o main.pvm
    polkatool disassemble main.pvm --output main.dis
    python3 ../merge.py main.dis main.psm.template main.out
    polkatool assemble main.out --output main.pvm
    rm main.elf main.dis main.out

clean:
    rm -f main.elf main.pvm
