set quiet
set dotenv-path := "../.env"

# Define default recipe
default: build run

run:
    printf "C example: "
    pvme call main.pvm entry 8 8 --host-functions "get_third_number:3"

build:
    $DOCKER run --rm -v{{justfile_directory()}}:/opt pvm clang-18 \
        --target=riscv32 \
        -march=rv32emc \
        -mabi=ilp32e \
        -nostdlib \
        -nodefaultlibs \
        -fpic \
        -fPIE \
        -mrelax \
        -ffast-math \
        -gdwarf-5 \
        -g3 \
        -O3 \
        -fno-exceptions \
        -fno-rtti \
        -Wl,--error-limit=0 \
        -Wl,--emit-relocs \
        -Wl,--no-relax \
        -Wl,--entry=entry \
        main.c \
        -o main.elf
    polkatool link -s main.elf -o main.pvm

clean:
    rm -f main.elf main.pvm
