set quiet
set dotenv-path := "../.env"

default: build run

build:
	#!/usr/bin/env bash

	mkdir build/
	jam-pvm-build ./jam-null-authorizer -o build/null-authorizer
	jam-pvm-build ./jam-bootstrap-service -o build/bootstrap-service

run:
    printf "is_authorized: TODO run this"

clean:
	rm -rf build/
