name: Examples (Docker)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: "run-examples"
  cancel-in-progress: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Just
      run: |
        # create ~/bin
        mkdir -p ~/bin

        # download and extract just to ~/bin/just
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin

        # add `~/bin` to the paths that your shell searches for executables
        # this line should be added to your shells initialization file,
        # e.g. `~/.bashrc` or `~/.zshrc`
        export PATH="$PATH:$HOME/bin"

        # just should now be executable
        just --help
    
    - name: Run Examples
      run: |
        export PATH="$PATH:$HOME/bin"
        just docker
        OUTPUT=$(just)

        if [[ "$output" == *"on_transfer: 4"* ]]; then
            echo "Found magic string, good"
        else
            echo "Did not find magic string, bad"
            exit 1
        fi
